project:
  type: manuscript

manuscript: 
  code-links: repo

execute:
  freeze: auto

format:
  html:
    toc: true
    other-links: 
      - text: akldogs R Package
        href: https://tesaunders.github.io/akldogs/
  docx: default
  pdf: default