---
title: "A Decade of Decline: Confronting the Reality of Auckland's Dog Control Crisis Using Auckland Council Data"
date: last-modified
author:
  - name: Thomas E. Saunders
    orcid: 0000-0003-1780-0314
    corresponding: true
    affiliation: University of Auckland
keywords: dog control, dog attacks, Auckland, euthanasia
abstract: A spate of fatal dog attacks have focussed attention on New Zealand's growing problem with roaming and aggressive dogs. Under the Dog Control Act 1996, Territorial Authorities are resposible for managing the harms associated with dogs in communities. Auckland Council's Animal Management division publishes selected high-level statistics related to it's dog control practices, but an examination of the underlying raw data in combination with data from it's annual reports reveals troubling trends for some of the most important metrics. The rate of attacks, impounds, and euthanasia of impounded dogs are all increasing due to an explosion in the dog population and a stretched shelter system. Attack rates are highest in South Auckland, and several breeds are over-represented in negative statistics. 
number-sections: true
bibliography: references.bib
csl: ama.csl
---

## Key Points

Over the last 10 years:

-   Auckland's dog population has increased by 14.5%, mostly since FY2020.
-   Registration and desexing rates have fallen, while the proportion of 'menacing' dogs has doubled to 1 in 20.
-   Dog attack rates have almost doubled from 6 to 10 attacks for every 1,000 dogs.
-   Impound rates in FY2025 are the second highest ever.
-   Euthanasia rates of impounded dogs have risen from 22% to 60%, mostly due to failed temperament tests and full shelters.
-   A small number of breeds are over-represented in attacks and impounds.
-   Local Boards in South Auckland have experienced lower rates of registration and desexing, and higher rates of attacks and impounds.

## Introduction

Four fatal dog attacks in New Zealand in the last four years have highlighted the increase in roaming and aggressive dogs in communities across the country.

-   Neville Thomson was killed in Katikati in August 2022 after being mauled by a pack of dogs owned by Abel Wira, whose property Thomson was staying at [@anonymous2025].
-   Elizabeth Whittaker was killed in October 2023 in Moerewa, Northland, in her backyard by dogs owned by another resident at the property [@anonymous2023].
-   Timothy Tu'uaki Rolleston-Bryan, a four-year-old boy, died in March 2025 following an attack on a Katikati property [@womanch2026].
-   Mihiata Te Rore died following an attack by three dogs while visiting a property in Kaihu, Northland, in February 2026 [@anonymous2026].

Recent media reports have drawn attention to dog attacks on other animals: from packs of roaming dogs killing sheep and calves in Northland [@anonymous2022], to the killing of dozens of pets in an Auckland suburb [@walton2024]. Blind Low Vision NZ is no longer placing guide dogs in certain South Auckland areas due to the high rates of dog attacks on guide dogs and their handlers [@anonymous2025a]. Residents in South Auckland communities report living in fear [@afemata2025], with elderly residents afraid to leave their homes, and children missing school for fear of encountering roaming aggressive dogs on their way to school, or within school grounds [@paddygower2025].

The Dog Control Act 1996 [@departmentofinternalaffairs1996] defines the obligations of dog owners, which include registering their dog, controlling their dog at all times, and ensuring their dog "does not injure, endanger, intimidate, or otherwise cause distress to any person." The Act also lays out the functions, duties, and powers of territorial authorities, which include minimising the dangers presented by dogs in the community and ensuring the public can "use streets and public amenities without fear of attack or intimidation by dogs." Auckland Council's approach to dog control is set out in it's Dog Management Bylaw [@aucklandcouncil2025a] and Policy on Dogs [@aucklandcouncil2025b]. Auckland Council's Animal Management division has around 150 permanent staff, including five area-based field teams (Central, East, North, South and West), a regional Barking and Registration team, a Proactive team, four animal shelters (Henderson, Manukau, Silverdale, and Pukekohe), a Veterinary Services team, and management, legal, and operational support staff.

Territorial authorities are required to collect and publish data relating to dog control policies and practices. Auckland Council's Animal Management division publishes a high-level summary of selected data in it's annual reports. I made a request under the Local Government Official Information and Meetings Act 1987 [@departmentofinternalaffairs1987] on 20 November 2025 for the full dataset compiled by the Council, which was fulfilled on 18 December 2025 (request #8140017948). The raw data is available as an R package called `akldogs`[@saunders2026], and the data is also available as cleaned .csv files in the package's [GitHub repository](https://github.com/tesaunders/akldogs/tree/main/data-raw). I also compiled data from Auckland Council Animal Management annual reports going back to FY2016, and this data can be found [here](/data). Below is an exploration of both data sources to understand Auckland's dog population and it's management. All years are financial years (1 July prev - 30 June current).

## Auckland Dog Population

There were 131,123 known dogs in the Auckland region as at 2025. As the dog population has increased, rates of registration and desexing have fallen. The proportion of dogs classified as 'menacing' under the Dog Control Act 1996, either due to their breed or behaviour, has doubled since 2016 to 1 in 20 dogs. A drop in the recorded dog population in 2018 was due to the removal of duplicate entries in the Auckland Council dog database, and in 2025 was due to the updating of the database during a registration campaign.

{{< embed notebooks/data-analysis.qmd#tbl-ownership >}}

Over 200 breeds are represented in the Auckland dog population. Labrador Retrievers remain the most popular at 11% of the Auckland dog population, with the top 10 also including the Staffordshire Bull Terrier and American Pit Bull Terrier, both automatically classified as 'menacing' under the Dog Control Act 1996.

{{< embed notebooks/data-analysis.qmd#tbl-top-breeds >}}

## Dog Attacks

The rate of dog attacks have almost doubled since 2016, from 6 attacks for every 1,000 dogs, to 10 attacks for every 1,000 dogs in 2025.

{{< embed notebooks/data-analysis.qmd#attacks-plot >}}

When Auckland Council Animal Management officers impound a dog because it has attacked a person, the attack severity is measured on a scale from 0 to 5. In all impounds for attacks in 2024 (the most recent year for the full impound data), Pit Bull Terriers or Staffordshire Terriers were responsible for the highest or second highest numbers of attacks in each severity category.

## Impounds

The rate of impounds per 1,000 dogs in the population reached 77.9 in 2025, the highest ever.

{{< embed notebooks/data-analysis.qmd#tbl-impound-rate >}}

The rate of impounds differed markedly by breed, with a 3 times difference even within the top 10.

{{< embed notebooks/data-analysis.qmd#tbl-impounds-breed >}}

The proportion of impounded dogs that were euthanised was steadily dropping between 2014 and 2021, when it reached a low of 21.7%. However, since then it climbed dramatically to reach 60.8% in 2025.

{{< embed notebooks/data-analysis.qmd#impound-outcome >}}

Most uncollected dogs were euthanised because they failed a temperament test (50.1%), and were therefore unsuitable for adoption. But a quarter of euthanised dogs were put down because the animal shelter was full.

Some dog breeds were significantly over-represented in euthanised dogs compared to the overall dog population. For example, Staffordshire Bull Terriers made up just over 6% of the dog population in 2024, but accounted for just over 30% of euthanised dogs in animal shelters. On the other hand, breeds like Labrador Retrievers were under-represented, making up just over 11% of the population but accounting for under 8% of euthanised dogs.

{{< embed notebooks/data-analysis.qmd#euth-breed >}}

The number of infringements issued by Animal Management officers under the Dog Control Act 1996 tripled between 2024 and 2025, from 6,387 to 17,430. The majority were issued for failing to register a dog. Despite this, the number of prosecutions and appeals brought by Animal Management has dropped from around 197 in 2016 to 141 in 2025.

## Regional Statistics

Auckland's 21 Local Boards can be grouped into 5 regions (North, South, East, West, and Central).

{{< embed notebooks/mapping.qmd#fig-regions-boards >}}

Most known dogs are found in the north, and the fewest are in the east.

{{< embed notebooks/data-analysis.qmd#tbl-region-pop >}}

Between 2021 and 2025, all Local Board areas experienced an increase in their dog population. While the median increase was 9%, Māngere-Ōtāhuhu and Ōtara-Papatoetoe Local Boards had significantly higher growth based on an analysis of the interquartile range.

{{< embed notebooks/data-analysis.qmd#tbl-board-pop >}}

Local Board areas differed greatly on rates of registration, desexing, dogs classified as menacing or dangerous, and the proportion of owners with a Responsible Dog Owner Licence.

<iframe src="outputs/reg_metrics.html" width="100%" height="850px" frameborder="0">

</iframe>

A Spearman rank correlation analysis showed that Local Boards with high current registrations tended to have higher rates of desexing and lower rates of classified animals, while those with higher rates of classifications tended to have lower rates of desexing.

{{< embed notebooks/data-analysis.qmd#spearman >}}

Local Boards differed in rates of desexing and classified dogs.

{{< embed notebooks/mapping.qmd#map-desex >}}

{{< embed notebooks/mapping.qmd#map-class >}}

A Chi-squared test revealed which dog breeds were over represented in each region, providing a snapshot of each region's unique breed profile.

{{< embed notebooks/data-analysis.qmd#region-breeds >}}

Local Boards differed greatly in the rate of dog attacks, impounds, and euthanasia of impounded dogs.

{{< embed notebooks/mapping.qmd#map-attacks >}}

{{< embed notebooks/mapping.qmd#map-impounds >}}

{{< embed notebooks/mapping.qmd#map-euth >}}

{{< embed notebooks/data-analysis.qmd#euth-board >}}

## Action

A number of professional and advocacy organisations have issued position statements and called for urgent policy reform to address the growing issue of dog control in New Zealand. All are united in their desire that dog control policy be evidence-based and preventative in nature. The New Zealand Veterinary Association[@newzealandveterinaryassociation2019] has called for

> a comprehensive plan delivered across multiple agencies that work together to address each factor. These agencies \[would\] include local and central government, animal control personnel, the veterinary profession, the medical profession, dog trainers and behaviourists, educators, dog breeders, dog welfare agencies and the media.

The New Zealand SPCA has issued position statements on dog safety[@newzealandspca] and breed-specific legislation[@newzealandspcaa], while the Paediatric Society of New Zealand[@thepaediatricsocietyofnewzealand2023] is concerned about the disproportionate impact of dog attacks on children. A number of academic studies and reviews have also investigated dog control in New Zealand[@duncan-sutherland2022; @duncan-sutherland2023; @smith2019; @duncan-sutherland2024; @duncan-sutherland2022].

Major recommendations include:

-   The application of kaupapa Māori approaches in the development and implementation of dog control strategies to ensure solutions are grounded in tikanga and reflect local aspirations.

-   The treatment of dog ownership as a privelege instead of a right, with a corresponding set of responsibilities reinforced through compulsory owner licensing and education.

-   The compulsory registration, desexing, and microchipping of all dogs.

-   The removal of breed-specific legislation due to a lack of evidence that breed is the largest contributing factor to dog bite events, that determining breed by appearance is unreliable, that it has failed to work overseas, and that it does not promote responsible dog ownership.

-   The introduction of a revised classification system based on behaviour instead of breed, which takes into account the context in whcih the aggressive behaviour ocurred, and which places increasingly stringent conditions on the dog and owner, while also providing a pathway for rehabilitation and the removal of the classification.

-   The regulation of breeding through a permit system administered by territorial authorities to recognise that breeding feeds directly into supply, and an oversupply of dog leads to overflowing shelters and roaming.

-   The introduction of targeted education programmes to first-time dog owners, owners whose dog has displayed aggresion or has attacked a person, and in areas with high incidences of dog attacks and roaming, delivered by a combination of dog breeders, veterniary clinics, and territorial authorities.

-   The resourcing of enforcement mechanisms to properly deal with irresponsible owners and their dogs within a consistent nation-wide framework, including supporting Animal Management Officers with the budgets, training, and powers they need to do their jobs properly.

-   The introduction of compulsory nation-wide notification of dog bites or dog-related injuries to the Territorial Authority in which the incident occurred.

-   The amendment of legislation to require that dogs are properly fenced or constrained on their property to prevent roaming and attacks, especially on children, the elderly, disabled, and other vulnerable groups.

-   The introduction of standardised data collection and reporting at the level of territorial authorities, which feeds into a national database of dog-related injuries, to better track trends and identify where interventions may be most effective.

-   The funding and conducting of research into interventions which reduce the incidence of dog-related injuries, especially in children.

## References

::: {#refs}
:::
